---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}-db
spec:
  ports:
  - port: {{ .Values.mysqlContainerPort }}
    protocol: TCP
    targetPort: {{ .Values.mysqltargetPort }}
  selector:
    app: {{ .Values.fullname }}-db
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: python-service11
spec:
  ports:
  - port: {{ .Values.appContainerPort }}
    protocol: TCP
    targetPort: {{ .Values.apptargetPort }}
  selector:
    app: flaskapi
  type: LoadBalancer
